// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ExamplesColumns holds the columns for the "examples" table.
	ExamplesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// ExamplesTable holds the schema information for the "examples" table.
	ExamplesTable = &schema.Table{
		Name:       "examples",
		Columns:    ExamplesColumns,
		PrimaryKey: []*schema.Column{ExamplesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ExamplesTable,
	}
)

func init() {
}
