// Code generated by ent, DO NOT EDIT.

package ent

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdate) SetNotEmptyName(value string) *StudentUpdate {
	if value != "" {
		return s.SetName(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdateOne) SetNotEmptyName(value string) *StudentUpdateOne {
	if value != "" {
		return s.SetName(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdate) SetNotEmptyAge(value int) *StudentUpdate {
	if value != 0 {
		return s.SetAge(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdateOne) SetNotEmptyAge(value int) *StudentUpdateOne {
	if value != 0 {
		return s.SetAge(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdate) SetNotEmptyAgeInt8(value int8) *StudentUpdate {
	if value != 0 {
		return s.SetAgeInt8(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdateOne) SetNotEmptyAgeInt8(value int8) *StudentUpdateOne {
	if value != 0 {
		return s.SetAgeInt8(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdate) SetNotEmptyAgeUint8(value uint8) *StudentUpdate {
	if value != 0 {
		return s.SetAgeUint8(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdateOne) SetNotEmptyAgeUint8(value uint8) *StudentUpdateOne {
	if value != 0 {
		return s.SetAgeUint8(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdate) SetNotEmptyAgeInt16(value int16) *StudentUpdate {
	if value != 0 {
		return s.SetAgeInt16(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdateOne) SetNotEmptyAgeInt16(value int16) *StudentUpdateOne {
	if value != 0 {
		return s.SetAgeInt16(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdate) SetNotEmptyAgeUint16(value uint16) *StudentUpdate {
	if value != 0 {
		return s.SetAgeUint16(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdateOne) SetNotEmptyAgeUint16(value uint16) *StudentUpdateOne {
	if value != 0 {
		return s.SetAgeUint16(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdate) SetNotEmptyAgeInt32(value int32) *StudentUpdate {
	if value != 0 {
		return s.SetAgeInt32(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdateOne) SetNotEmptyAgeInt32(value int32) *StudentUpdateOne {
	if value != 0 {
		return s.SetAgeInt32(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdate) SetNotEmptyAgeUint32(value uint32) *StudentUpdate {
	if value != 0 {
		return s.SetAgeUint32(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdateOne) SetNotEmptyAgeUint32(value uint32) *StudentUpdateOne {
	if value != 0 {
		return s.SetAgeUint32(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdate) SetNotEmptyAgeInt64(value int64) *StudentUpdate {
	if value != 0 {
		return s.SetAgeInt64(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdateOne) SetNotEmptyAgeInt64(value int64) *StudentUpdateOne {
	if value != 0 {
		return s.SetAgeInt64(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdate) SetNotEmptyAgeUint64(value uint64) *StudentUpdate {
	if value != 0 {
		return s.SetAgeUint64(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdateOne) SetNotEmptyAgeUint64(value uint64) *StudentUpdateOne {
	if value != 0 {
		return s.SetAgeUint64(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdate) SetNotEmptyAgeInt(value int) *StudentUpdate {
	if value != 0 {
		return s.SetAgeInt(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdateOne) SetNotEmptyAgeInt(value int) *StudentUpdateOne {
	if value != 0 {
		return s.SetAgeInt(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdate) SetNotEmptyAgeUint(value uint) *StudentUpdate {
	if value != 0 {
		return s.SetAgeUint(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdateOne) SetNotEmptyAgeUint(value uint) *StudentUpdateOne {
	if value != 0 {
		return s.SetAgeUint(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdate) SetNotEmptyWeightFloat(value float64) *StudentUpdate {
	if value != 0 {
		return s.SetWeightFloat(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdateOne) SetNotEmptyWeightFloat(value float64) *StudentUpdateOne {
	if value != 0 {
		return s.SetWeightFloat(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdate) SetNotEmptyWeightFloat32(value float32) *StudentUpdate {
	if value != 0 {
		return s.SetWeightFloat32(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdateOne) SetNotEmptyWeightFloat32(value float32) *StudentUpdateOne {
	if value != 0 {
		return s.SetWeightFloat32(value)
	}
	return s
}
