// Code generated by ent, DO NOT EDIT.

package ent

import "time"

// set field if value's pointer is not nil.
func (s *StudentUpdate) SetNotNilUpdatedAt(value *time.Time) *StudentUpdate {
	if value != nil {
		return s.SetUpdatedAt(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentUpdateOne) SetNotNilUpdatedAt(value *time.Time) *StudentUpdateOne {
	if value != nil {
		return s.SetUpdatedAt(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentCreate) SetNotNilUpdatedAt(value *time.Time) *StudentCreate {
	if value != nil {
		return s.SetUpdatedAt(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentUpdate) SetNotNilName(value *string) *StudentUpdate {
	if value != nil {
		return s.SetName(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentUpdateOne) SetNotNilName(value *string) *StudentUpdateOne {
	if value != nil {
		return s.SetName(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentCreate) SetNotNilName(value *string) *StudentCreate {
	if value != nil {
		return s.SetName(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentUpdate) SetNotNilAge(value *int16) *StudentUpdate {
	if value != nil {
		return s.SetAge(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentUpdateOne) SetNotNilAge(value *int16) *StudentUpdateOne {
	if value != nil {
		return s.SetAge(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentCreate) SetNotNilAge(value *int16) *StudentCreate {
	if value != nil {
		return s.SetAge(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentUpdate) SetNotNilAddress(value *string) *StudentUpdate {
	if value != nil {
		return s.SetAddress(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentUpdateOne) SetNotNilAddress(value *string) *StudentUpdateOne {
	if value != nil {
		return s.SetAddress(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentCreate) SetNotNilAddress(value *string) *StudentCreate {
	if value != nil {
		return s.SetAddress(*value)
	}
	return s
}
